apiVersion: v1
kind: Pod 
metadata:
    name: hello-world
spec: 
    containers:
    - image: tomox1001/wdpress
      imagePullPolicy: Always
      name: hello-world
      env:
      - name: WDPRESS_MESSAGE
        valueFrom: 
           configMapKeyRef:
               name: hello-world-config 
               key: hello-world.message
