apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
    name: hello-world
spec:
    replicas: 3
    template: 
        metadata: 
            labels:
                name: hello-world
        spec:
            containers:
                - image: tomox1001/wdpress
                  imagePullPolicy: Always 
                  name: hello-world
